name: NodeJS with Webpack

on:
  push:
    branches: 
      - development
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Lint
        run: npx eslint .

  build:
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4

    - name: Build
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        npm install
        npx run build
        
  deployment:
    runs-on: ubuntu-latest
    needs: [build, lint]
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Deploy Development
        if: github.head_ref == 'development'
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET_DEV }}
          EXCLUDE: "/.gitignore, /node_modules/, /index.html, /README.md, /package.json, /src/, /eslintrc.json, /package-lock.json, /vite.config.js, /.git/, /logos/, /.prettierignore, /.gitattributes, /mapthumbnails/, /.prettierrc, /.github/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
  
      - name: Deploy Production
        if: github.head_ref == 'main'
        run: |
          todo
