name: NodeJS with Webpack

on:
  push:
    branches: 
      - development
      - main
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Dev dependencies
        run: npm install --save-dev
      - name: Check eslint
        run: npm run lint
      - name: Check prettier
        run: npm run prettier-check

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: npm run build
        
  deployment:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: npm run build
      - name: List files
        run: ls -la
      - name: Deploy Development
        if: github.ref_name == 'development'
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET_DEV }}
          EXCLUDE: "/.gitignore, /node_modules/, /index.html, /README.md, /package.json, /src/, /eslintrc.json, /package-lock.json, /vite.config.js, /.git/, /logos/, /.prettierignore, /.gitattributes, /mapthumbnails/, /.prettierrc, /.github/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
  
      - name: Deploy Production
        if: github.head_ref == 'main'
        run: |
          todo
