name: Validate Pull Requests

on:
  pull_request:

jobs:
  style_check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache: 'npm'
      - name: Check eslint
        run: npx eslint src
      - name: Check prettier
        run: npx prettier src --check
    
  build_succeeds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_website
        with:
          node-version: lts/iron
          artifact-name: website
